### ISSUE TITLE
`Converter` exporters

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondolib#8]
## Overview
`mondo-ingest` utilizes SemanticSQL, which requires prefix maps in CSV form. We should create our own function in `mondolib` (unless Charlie thinks it's a good idea for this functionality to go in the `curies` package) that can generate this CSV so that we have 1 less place to maintain mappings.

## Sub-tasks
- [x] 1. Create exporter for SemanticSQL format: `prefixes.csv` (https://github.com/biopragmatics/curies/issues/106)
- [x] 2. Create exporter for `robot --add-prefixes` format: `context.json` (https://github.com/biopragmatics/curies/issues/106) ([docs](https://curies.readthedocs.io/en/latest/api/curies.write_jsonld_context.html))
- [ ] 3. **Utilize these exporters**: Goals using (1) and (2) should depend on goals that create them.
- [ ] 4. Update `docs/developer/add-new-source.md`: Remove sections about the above 2 files needing to be statically updated.

### Context
Comments in the synchronization: subclass axioms PR: [1](https://github.com/monarch-initiative/mondo-ingest/pull/363#discussion_r1328015440), [2](https://github.com/monarch-initiative/mondo-ingest/pull/363#discussion_r1328019917)

### Possible design
I think we should maintain these static files:
- `metadata/mondo.sssom.config.yml`
- `metadata/SOURCE.yml` for each source

Then, we should have some means of reading these in and instantiating a `curies.Converter` and from that export to the needed formats.

## Related
- Probably solve root of problem here: https://github.com/biopragmatics/curies/issues/106
- Do this after problem solved: https://github.com/monarch-initiative/mondo-ingest/issues/146
- Mirror issue: https://github.com/monarch-initiative/mondo-ingest/issues/371

**Comment by matentzn** [comment]
Fantastic idea! THANK YOU!

**Comment by joeflack4** [comment]
This topic came up when working on https://github.com/monarch-initiative/mondo-ingest/pull/394.

Nico suggestion on how to do this:
> Start with EPM. Load into Converter. Then do `.bimap()`, and it can generate the plain flat bimap which I can save as CSV.

**Comment by cthoyt** [comment]
@joeflack4 can you point me towards the code that saves these CSVs? maybe worth having an I/O function upstream in `curies` (or to update SemanticSQL to use standard file formats like EPMs ;))

**Comment by joeflack4** [comment]
@cthoyt I appreciate you chiming in! I wrote in the OP that "unless Charlie thinks it's a good idea for this functionality to go in the curies package", but I think actually we would prefer that.

I don't foresee SemanticSQL having the bandwidth to add EPMs now but I could be wrong.

Here's an example of a `prefixes.csv` compatible with SemanticSQL: https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/config/prefixes.csv
The two columns are `prefix` and `base`. In `curies`, `base` is called `uri prefix`, so I guess there are basically two options:
a. `curies` could have like a `.to_csv()` and call the 2nd column` uri_prefix`, and then for `mondo-ingest` purposes or other SemnaticSQL users, we'd use this method, but then have to change the 2nd column header on our end.
b. `curies` `.to_csv()` could have like a `format` param with values like `standard` and `semanticsql`, or just a boolean `semanticsql` param.

Actually though I just realized I am not sure if the headers (`prefix` and `base`) even matter to SemanticSQL. Perhaps it only cares about the column order? I don't see anything about the CSV in [the docs](https://github.com/INCATools/semantic-sql).
